
// Generated by scripts/prebuild.js
// Any changes done to this file will disappear on build
export const APP_METADATA = {
    APP_VERSION: '7f7431aa1144a64f0c7efc98d8e5337a627c57dd',
    APP_BUILD_DATE: '2017-12-05T11:18:29.733Z',
    GIT_REVISION: '7f7431aa1144a64f0c7efc98d8e5337a627c57dd',
};
