
// Generated by scripts/prebuild.js
// Any changes done to this file will disappear on build
export const APP_METADATA = {
    APP_VERSION: 'be01e726713e447788be0481e5bb46c2d855c070',
    APP_BUILD_DATE: '2017-12-04T14:52:13.859Z',
    GIT_REVISION: 'be01e726713e447788be0481e5bb46c2d855c070',
};
