export enum UNI_CONTROL_TYPES {
    AUTOCOMPLETE,//0
    COMBOBOX,//1
    DATEPICKER,//2
    DROPDOWN,//3
    MASKED,//4
    MULTISELECT,//5
    NUMERIC,//6
    RADIO,//7
    CHECKBOX,//8
    RADIOGROUP,//9
    TEXT,//10
    EMAIL,//11
    PASSWORD,//12
    HYPERLINK
}
