const fs = require('fs-extra')
const chokidar = require('chokidar');
const { copyFiles } = require('./config');

// Read and delete the temporary config file generated by config-selector.js
const config = JSON.parse(fs.readFileSync('./src/config/tmp_watch_config.json'));
fs.unlinkSync('./src/config/tmp_watch_config.json');

// Set up watcher
const watcher = chokidar.watch([
    `./src/config/themes/${config.themeFolder}`,
    `./src/config/environments/${config.envFile}`
], {
    persistent: true,
    ignoreInitial: true
});

let debouncer;
watcher.on('all', (event, path) => {
    clearTimeout(debouncer);
    debouncer = setTimeout(() => {
        debouncer = null;

        console.log(event, path);

        copyFiles(config.themeFolder, config.envFile);
    }, 200);
});