// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/191bc9e02d72d02c6c95bbb6cf5ebd1474a49a51/base64-js/base64-js.d.ts
declare module 'base64-js' {

    export function toByteArray(encoded: string): Uint8Array;
    export function fromByteArray(bytes: Uint8Array): string;
}
