name: CI-Merge-master->RC

on:
  push:
    branches:
      - 'master'
jobs:
  merge_master_rc:
    runs-on: ubuntu-latest
    outputs:
      test: ${{steps.myid.outputs.myvar}}
    steps:
      - uses: actions/checkout@master
      - name: run stuff
        id: myid
        run: echo "::set-output name=myvar=yay"
  
  merge_rc_develop:
    runs-on: ubuntu-latest
    needs: merge_master_rc
    steps:
      - name: Debug 
        run: echo ${{needs.merge_master_rc.outputs.test}}
